import 'package:pmv_tracker/core/constants.dart';

/// Data model representing a single PMV report
class PmvReport {
  final int? id; // Will be auto-generated by Supabase
  final double latitude;
  final double longitude;
  final String routeName;
  final String status; // 'waiting', 'onboard', 'full'
  final DateTime reportedAt;
  final DateTime expiresAt;

  PmvReport({
    this.id,
    required this.latitude,
    required this.longitude,
    required this.routeName,
    required this.status,
    DateTime? reportedAt,
    DateTime? expiresAt,
  })  : reportedAt = reportedAt ?? DateTime.now().toUtc(),
        expiresAt = expiresAt ??
            DateTime.now()
                .toUtc()
                .add(const Duration(minutes: AppConstants.reportExpiryMinutes));

  // Convert this model to a Map for saving to Supabase
  Map<String, dynamic> toMap() {
    return {
      'latitude': latitude,
      'longitude': longitude,
      'route_name': routeName,
      'status': status,
      'reported_at': reportedAt.toIso8601String(),
      'expires_at': expiresAt.toIso8601String(),
    };
  }

  // Create a model from a Map (when reading from Supabase)
  factory PmvReport.fromMap(Map<String, dynamic> map) {
    return PmvReport(
      id: map['id'],
      latitude: map['latitude'],
      longitude: map['longitude'],
      routeName: map['route_name'],
      status: map['status'],
      reportedAt: DateTime.parse(map['reported_at']),
      expiresAt: DateTime.parse(map['expires_at']),
    );
  }
}
